In [1]:
# Importing libraries

import pandas as pd
import numpy as np

In [2]:
# reading data from file
dataset=pd.read_csv("hmnist_28_28_RGB.csv")

In [3]:
dataset.head(10)

pixel0000  pixel0001  pixel0002  pixel0003  pixel0004  pixel0005  \
0        192        153        193        195        155        192   
1         25         14         30         68         48         75   
2        192        138        153        200        145        163   
3         38         19         30         95         59         72   
4        158        113        139        194        144        174   
5          8          1          3         19          5         10   
6        194        147        137        197        148        139   
7        161        121        105        169        128        119   
8        125         84         85        165        114        118   
9        228        179        194        227        174        191   

   pixel0006  pixel0007  pixel0008  pixel0009  ...  pixel2343  pixel2344  \
0        197        154        185        202  ...        173        124   
1        123         93        126        158  ...         60         39   
2        201        142        160        206  ...        167        129   
3        143        103        119        171  ...         44         26   
4        215        162        191        225  ...        209        166   
5         26          8         13         34  ...         12          3   
6        197        148        132        200  ...        211        160   
7        172        129        116        176  ...        141        103   
8        181        120        125        188  ...        119         80   
9        226        165        182        215  ...        217        142   

   pixel2345  pixel2346  pixel2347  pixel2348  pixel2349  pixel2350  \
0        138        183        147        166        185        154   
1         55         25         14         28         25         14   
2        143        159        124        142        136        104   
3         36         25         12         17         25         12   
4        185        172        135        149        109         78   
5          7          5          0          1          4          0   
6        163        211        162        166        208        162   
7         92         87         59         56         32         18   
8         79         62         35         41         19          8   
9        156        219        154        166        216        146   

   pixel2351  label  
0        177      2  
1         27      2  
2        117      2  
3         15      2  
4         92      2  
5          0      2  
6        166      2  
7         19      2  
8         13      2  
9        154      2  

[10 rows x 2353 columns]

In [4]:
X=dataset.iloc[:,:-1]
Y=dataset.iloc[:,-1:] 

In [5]:
X.head()

pixel0000  pixel0001  pixel0002  pixel0003  pixel0004  pixel0005  \
0        192        153        193        195        155        192   
1         25         14         30         68         48         75   
2        192        138        153        200        145        163   
3         38         19         30         95         59         72   
4        158        113        139        194        144        174   

   pixel0006  pixel0007  pixel0008  pixel0009  ...  pixel2342  pixel2343  \
0        197        154        185        202  ...        134        173   
1        123         93        126        158  ...         82         60   
2        201        142        160        206  ...        149        167   
3        143        103        119        171  ...         73         44   
4        215        162        191        225  ...        201        209   

   pixel2344  pixel2345  pixel2346  pixel2347  pixel2348  pixel2349  \
0        124        138        183        147        166        185   
1         39         55         25         14         28         25   
2        129        143        159        124        142        136   
3         26         36         25         12         17         25   
4        166        185        172        135        149        109   

   pixel2350  pixel2351  
0        154        177  
1         14         27  
2        104        117  
3         12         15  
4         78         92  

[5 rows x 2352 columns]

In [6]:
Y.head()

label
0      2
1      2
2      2
3      2
4      2

In [7]:
# scaling data 
from sklearn import preprocessing
X = preprocessing.scale(X)

In [8]:
# splitting train and test data we are taking 10% of data as test data
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.1)

In [26]:
### Voting classifier

from sklearn.linear_model import LogisticRegression 
from sklearn.svm import SVC 
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier

from sklearn.ensemble import VotingClassifier


model1 = LogisticRegression(random_state=1)
model2 = DecisionTreeClassifier(random_state=1)
model3 = KNeighborsClassifier()


model = VotingClassifier(estimators=[('lr', model1), ('dt', model2), ('knn', model3)], voting='hard')
model.fit(X_train,y_train)
model.score(X_test,y_test)

C:\Users\Arpit\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Arpit\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.7245508982035929

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm

In [10]:
model=RandomForestClassifier(n_estimators=200)
#model = svm.SVC()
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.1)

In [11]:
model.fit(X_train,y_train)

<ipython-input-11-b7a8c64777c1>:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model.fit(X_train,y_train)


RandomForestClassifier(n_estimators=200)

In [12]:
import pickle 
#save_model = pickle.dumps(model) 
#cancer_prediction = pickle.loads(save_model) 

filename = 'Cancer_finalized_model.pickle'
pickle.dump(model, open(filename, 'wb'))

cancer_prediction = pickle.load(open(filename, 'rb'))


y_pred=cancer_prediction.predict(X_test)


In [27]:
from sklearn import metrics
#Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.7465069860279441


In [28]:
# creating function to map the type with predicted result
def CancerPrediction(num):
    if num==0:
        return 'Actinic keratoses'
    if num==1:
        return 'Basal cell carcinoma'
    if num==2:
        return 'Benign keratosis-like lesions'
    if num==3:
        return 'Dermatofibroma'
    if num==4:
        return 'Melanoma'
    if num==5:
        return "Melanocytic nevi"
    if num==6:
        return 'Vascular lesions'

In [29]:
np.unique(Y) # 7 unique values are being predicted i.e. 7 types of cancer 

array([0, 1, 2, 3, 4, 5, 6], dtype=int64)

In [30]:
#taking image and predicting type
from PIL import Image

im = Image.open("C:\\Users\\Arpit\\HAM10000 dataset\\HAM10000_images_part_2\\ISIC_0029314.jpg")
pixels = np.matrix(im.getdata())


print(pixels)

[[225 123 137]
 [220 118 132]
 [226 124 138]
 ...
 [224 147 155]
 [223 148 152]
 [228 149 154]]


In [31]:
pixels.shape

(270000, 3)

In [32]:
from PIL import Image 
img = Image.open("C:\\Users\\Arpit\\HAM10000 dataset\\HAM10000_images_part_2\\ISIC_0029314.jpg") 
img = img.resize((28,28)) 
img.save("C:\\Users\\Arpit\\Desktop\\resized_picture.jpg")

In [33]:
pixels = np.matrix(img.getdata())
pixels

matrix([[227, 127, 137],
        [224, 115, 117],
        [225, 117, 119],
        ...,
        [234, 158, 164],
        [231, 150, 157],
        [227, 150, 155]])

In [20]:
pixels.shape

(784, 3)

In [21]:
ini_array1 = np.array(pixels) 

In [22]:
# flatten result array
result = ini_array1.flatten() 

In [23]:
result

array([227, 127, 137, ..., 227, 150, 155])

In [24]:
temp=result.reshape(1,-1)

In [34]:
# predicting and mapping predictions
model.predict(temp)[0]
print(CancerPrediction(model.predict(temp)[0]))

Melanoma
